version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
      time: "08:00"
    groups:
      npm-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
      time: "08:00"
    groups:
      github-actions:
        patterns:
          - "*"
