packages:
  - "."
saveExact: true
minimumReleaseAge: 10080
minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - pnpm
  - "@pnpm/exe.*"
update:
  githubActions: true
allowBuilds:
  "@sentry/cli": false
  esbuild: true
  lefthook: true
  sharp: true
