options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/score-watcher-develop-env/versions/latest
      env: _ENV_FILE

steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    secretEnv:
      - "_ENV_FILE"
    args:
      - "-c"
      - |
        # Secret Manager の内容を .env に書き出し
        printf '%s' "$_ENV_FILE" > .env

        # ルートディレクトリをビルドコンテキストとして Docker イメージをビルド
        docker build \
          -f infra/Dockerfile.main \
          -t gcr.io/$PROJECT_ID/score-watcher-main \
          .

images:
  - "gcr.io/$PROJECT_ID/score-watcher-main"
