import { NextPage } from "next";
import Head from "next/head";

import RuleCard, { RuleCardProps } from "components/RuleCard";

const ruleList: RuleCardProps[] = [
  {
    id: "normal",
    name: "スコア計算",
    description: "単純なスコアを計算します。",
  },
];

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next Score Watcher</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>形式一覧</h2>
        {ruleList.map((rule) => (
          <RuleCard
            key={rule.id}
            id={rule.id}
            name={rule.name}
            description={rule.description}
          />
        ))}
      </main>
    </div>
  );
};

export default Home;
