import { NextPageWithLayout } from "next";
import Head from "next/head";

import { Container } from "@chakra-ui/react";

import GameList from "#/components/GameList";
import Header from "#/components/Header";
import LoadPlayer from "#/components/LoadPlayer";
import LoadQuiz from "#/components/LoadQuiz";
import RuleList from "#/components/RuleList";
import UpdateModal from "#/components/UpdateModal";
import { Layout } from "#/layouts/Layout";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Next Score Watcher</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GameList />
      <RuleList />
      <LoadQuiz />
      <LoadPlayer />
      <UpdateModal />
    </>
  );
};

Home.getLayout = (page) => <Layout>{page}</Layout>;

export default Home;
