import Head from "next/head";

import { NextPage } from "next";
import { Card, Container } from "semantic-ui-react";

import GameList from "#/components/GameList";
import LoadQuiz from "#/components/LoadQuiz";
import RuleCard from "#/components/RuleCard";
import state from "#/utils/state";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next Score Watcher</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <h1>Next Score Watcher</h1>
          <GameList />
          <h2>形式一覧</h2>
          <Card.Group>
            {(Object.keys(state.rules) as (keyof typeof state.rules)[]).map(
              (id) => (
                <RuleCard
                  key={id}
                  id={id}
                  name={state.rules[id].name}
                  description={state.rules[id].description}
                />
              )
            )}
          </Card.Group>
          <h2>問題の読み込み</h2>
          <LoadQuiz />
        </Container>
      </main>
    </div>
  );
};

export default Home;
