name: Codecheck

on:
  pull_request:
    branches: ["main", "develop"]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10.28.0
      - name: Setup Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: "24"
          cache: "pnpm"
      - name: 依存関係をインストール
        run: pnpm install --frozen-lockfile
      - name: Lintチェック
        run: pnpm run lint
      - name: Formatチェック
        run: pnpm run format
      - name: Stylelintチェック
        run: pnpm run stylelint
